import 'dotenv/config';
import { PrismaClient } from '../src/generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const words = [
  { term: 'Abate', definition: 'v. to become less active or less intense or less in amount', example: 'As I began my speech my feelings of nervousness quickly abated.' },
  { term: 'Abrupt', definition: 'adj. Sudden and unexpected.', example: 'His abrupt departure surprised everyone.' },
  { term: 'Abstract', definition: 'adj. existing purely in the mind; not representing actual reality', example: 'Julie had trouble understanding the appeal of the abstract painting.' },
  { term: 'Abysmal', definition: 'adj. extremely bad', example: 'I got an abysmal grade on my research paper!' },
  { term: 'Acceptable', definition: 'adj. Satisfactory or permissible.', example: "The teacher deemed Sara's late assignment acceptable." },
  { term: 'Accidental', definition: 'adj. Happening by chance.', example: 'The oil spill was purely accidental.' },
  { term: 'Accommodate', definition: 'v. To provide space or make adjustments.', example: 'The Grand Hotel can accommodate up to 500 guests.' },
  { term: 'Accuracy', definition: 'n. The quality of being correct or precise.', example: "The accuracy of the intern's report was impressive." },
  { term: 'Acknowledge', definition: 'v. To recognize or admit the truth.', example: 'She refused to acknowledge her mistake.' },
  { term: 'Acquired', definition: 'adj. Gained through effort or experience.', example: 'Edmund had acquired a taste for fine wine.' },
  { term: 'Adapt', definition: 'v. To adjust to new conditions.', example: 'Newly-released animals generally adapt to their environments over time.' },
  { term: 'Adept', definition: "adj. having knowledge or skill (usually in a particular area)", example: "Beth loves playing the piano but she's especially adept at the violin." },
  { term: 'Adequate', definition: 'adj. having sufficient qualifications to meet a specific task or purpose', example: "Though his resume was adequate the company doubted whether he'd be a good fit." },
  { term: 'Adhere', definition: 'v. To stick to or follow closely.', example: "You must adhere to the rules if you don't want to get in trouble." },
  { term: 'Adjust', definition: 'v. To modify or change slightly.', example: 'He had to adjust his seat for comfort.' },
  { term: 'Admire', definition: 'v. To respect or look up to.', example: "I admire my mother's dedication to her work." },
  { term: 'Advantageous', definition: 'adj. Beneficial or useful.', example: 'Speaking multiple languages is advantageous.' },
  { term: 'Advent', definition: 'n. the arrival or creation of something', example: 'The world has never been the same since the advent of the light bulb.' },
  { term: 'Advise', definition: 'v. To recommend or give guidance.', example: 'I advise you to study for the exam.' },
  { term: 'Aggravate', definition: 'v. To worsen or intensify.', example: 'Scratching the rash will only aggravate it.' },
  { term: 'Aggressive', definition: 'adj. Forceful or overly assertive.', example: "The man's aggressive tone made everyone uneasy." },
  { term: 'Allude', definition: 'v. to make a secretive mention of something', example: "She alluded to the problem at hand but didn't say anything more about it." },
  { term: 'Ambiguity', definition: 'n. Uncertainty or multiple interpretations.', example: 'The ambiguity in his vague statement caused confusion.' },
  { term: 'Ambivalence', definition: 'n. Mixed or conflicting feelings.', example: 'Jessie felt ambivalence about moving to a new city.' },
  { term: 'Ameliorate', definition: 'v. To improve or make better.', example: 'The new policy aims to ameliorate working conditions for all employees.' },
  { term: 'Amplify', definition: 'v. To increase in size or effect.', example: 'The microphone will amplify your voice.' },
  { term: 'Amusing', definition: 'adj. Entertaining or humorous.', example: "Jason's joke was quite amusing." },
  { term: 'Analogous', definition: 'adj. similar but not identical', example: 'Green onions are considered analogous to spring onions.' },
  { term: 'Annotate', definition: 'v. To add notes or comments.', example: 'Please annotate the medical text with your observations.' },
  { term: 'Announce', definition: 'v. To make a public statement.', example: 'The CEO will announce the new policy tomorrow.' },
  { term: 'Anomaly', definition: 'n. something different from the norm', example: 'This result is an anomaly and very rarely happens.' },
  { term: 'Antagonistic', definition: 'adj. Showing hostility or opposition.', example: 'His antagonistic behavior created tension at work.' },
  { term: 'Antecedent', definition: 'n. A preceding event or condition.', example: 'The antecedent to the war was political unrest.' },
  { term: 'Anticipate', definition: 'v. To expect or predict.', example: 'Does the weatherman anticipate a rise in temperatures next week?' },
  { term: 'Antipathy', definition: 'n. a strong feeling of dislike', example: 'Her antipathy toward the professor was obvious: she rolled her eyes whenever he entered the classroom.' },
  { term: 'Apex', definition: 'n. the highest point of something', example: 'The spring play was the apex of our school year.' },
  { term: 'Appropriate', definition: 'adj. Suitable for a specific situation.', example: "Lily's velvet dress was appropriate for the formal occasion." },
  { term: 'Approximate', definition: 'adj. Nearly accurate or close to.', example: 'The approximate cost is $50.' },
  { term: 'Arcane', definition: 'adj. Mysterious or known by few.', example: 'The ancient book contained arcane knowledge.' },
  { term: 'Arduous', definition: 'adj. Difficult and requiring effort.', example: 'The steep hike up the mountain was arduous.' },
  { term: 'Assemble', definition: 'v. To gather or put together.', example: 'We need to assemble the bed if we want a place to sleep tonight.' },
  { term: 'Austere', definition: 'adj. extremely plain; stern and forbidding; relating to self-denial', example: 'He lived in a small austere cabin in the middle of the woods.' },
  { term: 'Avoid', definition: 'v. To stay away from or prevent.', example: 'Mara hates fighting so she always tries to avoid conflict.' },
  { term: 'Beneficial', definition: 'adj. Producing good results.', example: 'A balanced diet is beneficial to your health.' },
  { term: 'Benevolent', definition: 'adj. kind and generous', example: 'Many cultures believe in benevolent spirits.' },
  { term: 'Bold', definition: 'adj. Courageous or striking.', example: 'Elsie made a bold move by quitting her job.' },
  { term: 'Borrow', definition: 'v. To take temporarily.', example: 'Libraries will let you borrow books for several weeks.' },
  { term: 'Buttress', definition: 'v. To support or strengthen.', example: 'The evidence will buttress his argument.' },
  { term: 'Bypass', definition: 'v. To go around or avoid.', example: 'We took a shortcut to bypass traffic.' },
  { term: 'Calibrate', definition: 'v. To adjust for precision.', example: 'The scientist had to calibrate the instrument to ensure his measurements were accurate.' },
  { term: 'Candid', definition: 'adj. direct and blunt', example: 'Josh is candid about his desire to become an actor.' },
  { term: 'Carelessly', definition: 'adv. Without caution.', example: 'He carelessly left his keys on the bus.' },
  { term: 'Catastrophic', definition: 'adj. Disastrous or causing great damage.', example: 'The catastrophic hurricane destroyed dozens of homes.' },
  { term: 'Cause', definition: 'n. A reason for an action or event.', example: "The fire's cause is still unknown." },
  { term: 'Characterization', definition: 'n. The way a character is described.', example: "The novel's characterization was deep and complex." },
  { term: 'Circumvent', definition: 'v. To find a way around.', example: 'They found a loophole to circumvent the rule.' },
  { term: 'Coincidence', definition: 'n. A surprising and unexpected event.', example: 'Meeting my neighbor at the airport was a coincidence.' },
  { term: 'Collaboration', definition: 'n. Working together on a task.', example: "The scientists' collaboration led to a breakthrough." },
  { term: 'Commercialization', definition: 'n. The process of making something a business.', example: 'The commercialization of the product increased sales.' },
  { term: 'Committed', definition: 'adj. Dedicated to a cause or task.', example: 'Ava is committed to her studies and always wants top grades.' },
  { term: 'Common', definition: 'adj. Occurring frequently or shared.', example: "It's very common for students to feel stressed before exams." },
  { term: 'Compelling', definition: 'adj. Captivating or persuasive.', example: 'The debater gave a compelling argument.' },
  { term: 'Competent', definition: 'adj. Having the necessary ability or skill.', example: 'Noah has worked at this job for a long time and is a competent engineer.' },
  { term: 'Complementary', definition: 'adj. Enhancing or completing another.', example: 'The artist and the engineer have skills that are complementary in the project.' },
  { term: 'Complexity', definition: 'n. The state of being intricate or complicated.', example: 'The complexity of the 1000 piece puzzle made it challenging.' },
  { term: 'Compose', definition: 'v. To create or write.', example: 'Jordan plans to compose a new symphony.' },
  { term: 'Compound', definition: 'v. To intensify or combine.', example: 'The traffic was compounded by bad weather.' },
  { term: 'Comprise', definition: 'v. To consist of or include.', example: 'The book comprises ten chapters.' },
  { term: 'Conceal', definition: 'v. To hide or keep secret.', example: 'Luca tried to conceal his disappointment.' },
  { term: 'Concede', definition: 'v. To admit or yield.', example: 'She conceded that she was wrong during the argument.' },
  { term: 'Conceptualize', definition: 'v. To form an idea or concept.', example: 'In this lab scientists conceptualize new theories on viruses.' },
  { term: 'Concerning', definition: 'adj. Causing worry or distress.', example: 'The news about the approaching hurricane is quite concerning.' },
  { term: 'Condition', definition: 'n. The state of something.', example: 'The car I bought is in excellent condition.' },
  { term: 'Confident', definition: 'adj. Feeling sure or self-assured.', example: 'Michael Jordan is confident in his abilities as a basketball player.' },
  { term: 'Conflated', definition: 'adj. Combined in a misleading way.', example: 'The two issues were conflated in the argument.' },
  { term: 'Conform', definition: 'v. To comply with rules or expectations.', example: 'The alternative rocker refuses to conform to societal norms.' },
  { term: 'Consensus', definition: 'n. General agreement.', example: 'The team finally reached a consensus on the decision.' },
  { term: 'Consistent', definition: 'adj. Acting in the same way over time.', example: "My grandmother's knitting is always consistent in quality." },
  { term: 'Conspicuous', definition: 'adj. Easily noticed or standing out.', example: "Veronica's red dress was conspicuous in the crowd." },
  { term: 'Constant', definition: 'adj. Occurring continuously.', example: "The criminal lived in constant fear that he'd be found out." },
  { term: 'Contentious', definition: 'adj. Causing disagreement or debate.', example: 'Politics are highly contentious these days.' },
  { term: 'Contingent', definition: 'adj. Dependent on something else.', example: 'Our family ski trip is contingent on the weather.' },
  { term: 'Contradict', definition: 'v. to be in contrast with', example: 'The camera footage contradicts his alibi.' },
  { term: 'Contrived', definition: 'adj. Artificial or overly planned.', example: "The movie's plot felt contrived and unrealistic." },
  { term: 'Controversial', definition: 'adj. Causing public disagreement.', example: "The judge's decision to free the criminal was highly controversial." },
  { term: 'Cordially', definition: 'adv. In a warm or friendly manner.', example: 'The two old friends greeted each other cordially.' },
  { term: 'Corroborate', definition: 'v. to provide evidence for; to back up a claim', example: 'The note signed by her father corroborates her claim that she was absent from class that day.' },
  { term: 'Costly', definition: 'adj. Expensive or requiring sacrifice.', example: 'The mistake was a costly one and caused the company to go bankrupt.' },
  { term: 'Counteract', definition: 'v. to work in opposition to', example: 'This ingredient seems to counteract the other ones.' },
  { term: 'Critical', definition: 'adj. Expressing analysis or judgment.', example: 'The review was highly critical of the film.' },
  { term: 'Criticize', definition: 'v. To express disapproval.', example: 'My father tends to criticize others harshly.' },
  { term: 'Deceptive', definition: 'adj. Misleading or dishonest.', example: 'The advertisement was deceptive in its claims of weight loss.' },
  { term: 'Deciding', definition: 'adj. Determining or influencing an outcome.', example: 'The final goal was the deciding factor in the match.' },
  { term: 'Decisive', definition: 'adj. Conclusive or firm.', example: "My boss's decisive leadership helped solve our company's crisis." },
  { term: 'Deficient', definition: 'adj. not enough in degree or amount', example: 'I feel as though the sources for my paper are deficient.' },
  { term: 'Defunct', definition: 'adj. No longer existing or functional.', example: 'After people stopped using fax machines the fax company became defunct.' },
  { term: 'Delegate', definition: 'v. To assign tasks or authority to others.', example: 'A good leader knows how to delegate responsibilities.' },
  { term: 'Deliberation', definition: 'n. Careful consideration or discussion.', example: 'After much deliberation they made their decision.' },
  { term: 'Delicate', definition: 'adj. Fragile or requiring careful handling.', example: 'The delicate glass sculpture broke easily.' },
  { term: 'Demarcate', definition: 'v. To set boundaries or distinguish.', example: 'The Tornio river demarcates the border between Sweden and Finland.' },
  { term: 'Derived', definition: 'adj. Obtained or developed from a source.', example: 'The word aqua is derived from Latin.' },
  { term: 'Despise', definition: 'v. To strongly dislike or look down upon.', example: 'The judge despises dishonesty.' },
  { term: 'Desultory', definition: 'adj. Lacking a clear plan or enthusiasm.', example: "The tired boy's desultory efforts did not impress the coach." },
  { term: 'Determine', definition: 'v. To establish or decide.', example: 'The final exam will determine your grade.' },
  { term: 'Deviate', definition: 'v. To move away from a set path or norm.', example: 'When the new evidence was uncovered the lawyer deviated from the original plan.' },
  { term: 'Devise', definition: 'v. to come up with a plan', example: 'Lana devised a plan to make herself famous.' },
  { term: 'Diminish', definition: 'v. To decrease in size or importance.', example: "The politician's influence has diminished over time." },
  { term: 'Directed', definition: 'adj. Managed or guided.', example: 'This new film was directed by a renowned artist.' },
  { term: 'Disagreement', definition: 'n. A difference of opinion.', example: 'An intense disagreement arose over the contract terms.' },
  { term: 'Disastrous', definition: 'adj. Causing great harm or failure.', example: 'The earthquake had disastrous consequences for the island.' },
  { term: 'Disconcerting', definition: 'adj. Causing discomfort or confusion.', example: "My girlfriend's sudden change in behavior is disconcerting." },
  { term: 'Discord', definition: 'n. disagreement', example: 'Disputes over money caused intense discord in the family.' },
  { term: 'Discount', definition: 'v. To disregard or reduce in value.', example: "The teacher discounted his students' concerns." },
  { term: 'Discourage', definition: 'v. To dissuade or deter.', example: 'Luna tried to discourage her brother from moving out of the house.' },
  { term: 'Discretion', definition: 'n. The ability to make responsible choices.', example: 'The detective handled the matter with great discretion.' },
  { term: 'Disengage', definition: 'v. To separate or withdraw.', example: 'I was exhausted so I tried to disengage from the argument.' },
  { term: 'Dismiss', definition: 'v. To reject or send away.', example: 'The teacher dismissed the idea to end class early.' },
  { term: 'Disorienting', definition: 'adj. Causing confusion or loss of direction.', example: 'The vast corn maze was disorienting.' },
  { term: 'Disparage', definition: "v. To belittle or speak negatively about.", example: "The politician disparaged his opponent's ideas on tax cuts." },
  { term: 'Disparate', definition: 'adj. Essentially different or unconnected.', example: 'Many European countries have disparate Christmas traditions.' },
  { term: 'Dispute', definition: 'n. A disagreement or argument.', example: 'The neighbors had a dispute over the new fence.' },
  { term: 'Distinct', definition: 'adj. Clearly different or separate.', example: 'My twin sons have distinct personalities.' },
  { term: 'Distract', definition: 'v. To divert attention.', example: 'The rattling noise distracted Javi from his work.' },
  { term: 'Distressed', definition: 'adj. Suffering from anxiety or pain.', example: "The woman looked distressed after the doctor's call." },
  { term: 'Diverge', definition: 'v. To move apart or differ.', example: "My parents' opinions on politics began to diverge as they grew older." },
  { term: 'Diverse', definition: 'adj. Showing variety or differences.', example: 'New York City has a diverse population.' },
  { term: 'Dominance', definition: 'n. The state of being in control or superior.', example: "The company's dominance in the market is evident." },
  { term: 'Dormant', definition: 'adj. Inactive but capable of becoming active.', example: 'The volcano beneath Mount Fuji has been dormant for centuries.' },
  { term: 'Dynamic', definition: 'adj. Constantly changing or energetic.', example: 'My coworker is a dynamic speaker who commands attention wherever she goes.' },
  { term: 'Earnest', definition: 'adj. Serious and sincere.', example: 'He felt terrible about breaking the mirror and made an earnest apology.' },
  { term: 'Eclipse', definition: 'v. To overshadow or surpass.', example: "The headliner's performance eclipsed all others in the concert." },
  { term: 'Eloquent', definition: 'adj. having refined or expressive communication skills in speaking or writing', example: 'His speech was not only eloquent but also extremely compelling.' },
  { term: 'Elusive', definition: 'adj. Hard to find or understand.', example: 'Nothing became clearer and the answer remained elusive.' },
  { term: 'Encompass', definition: 'v. To include or surround.', example: 'The project encompasses multiple disciplines.' },
  { term: 'Encounter', definition: 'v. To meet or face unexpectedly.', example: 'She encountered an old friend at the store.' },
  { term: 'Encourage', definition: 'v. To support or inspire.', example: 'Teachers often encourage students to ask questions.' },
  { term: 'Enduring', definition: 'adj. Lasting over time.', example: 'Their 50-year friendship is enduring.' },
  { term: 'Evidence', definition: 'n. Information that supports a conclusion.', example: 'There is strong evidence to support the theory.' },
  { term: 'Evoke', definition: 'v. to draw forth or call up', example: 'Horror movies are great at evoking fear.' },
  { term: 'Exacerbate', definition: 'v. To make a problem worse.', example: 'His rude comments only exacerbated the tense situation.' },
  { term: 'Exactitude', definition: 'n. The quality of being precise or accurate.', example: "The scientist's exactitude ensured reliable results." },
  { term: 'Exaggerate', definition: 'v. To overstate or magnify beyond the truth.', example: 'My cousin tends to exaggerate his achievements.' },
  { term: 'Exceed', definition: 'v. To go beyond a limit.', example: 'The driver exceeded the speed limit by nearly 30 miles an hour.' },
  { term: 'Exemplify', definition: 'v. To serve as a typical example of something.', example: "The woman's kindness to her neighbors exemplifies true generosity." },
  { term: 'Exhaustive', definition: 'adj. Thorough and complete.', example: 'The 300-page report provided an exhaustive analysis.' },
  { term: 'Expansion', definition: 'n. The act of increasing in size or scope.', example: "The company's expansion into international markets has been successful so far." },
  { term: 'Expensive', definition: 'adj. Costing a lot of money.', example: "My sister's diamond ring was extremely expensive." },
  { term: 'Experiment', definition: 'n. A test to discover something new.', example: 'The scientist conducted an experiment to test the theory.' },
  { term: 'Explicable', definition: 'adj. Able to be explained.', example: 'Once I knew the full story my boyfriend\'s actions were explicable given the circumstances.' },
  { term: 'Exploit', definition: 'v. To take advantage of something unfairly.', example: 'The mining company was accused of exploiting workers.' },
  { term: 'Extensive', definition: 'adj. Covering a large area or scope.', example: 'The Art Institute of Chicago has an extensive Impressionist collection.' },
  { term: 'Extraneous', definition: 'adj. Unrelated or unnecessary.', example: "The report contained too much extraneous information that didn't matter to the trial." },
  { term: 'Fabricate', definition: 'v. To invent or create often dishonestly.', example: 'The criminal fabricated evidence to support his bogus claim.' },
  { term: 'Foretell', definition: 'v. To predict or anticipate.', example: 'Ancient prophecies foretold the end of the world.' },
  { term: 'Foster', definition: 'v. To encourage or promote development.', example: 'Teachers should strive to foster creativity in students.' },
  { term: 'Fragile', definition: 'adj. Easily broken or delicate.', example: 'The glass vase is very fragile.' },
  { term: 'Fruitless', definition: 'adj. Failing to achieve desired results.', example: 'Their search for survivors was fruitless.' },
  { term: 'Genuine', definition: 'adj. Authentic or real.', example: 'His apology seemed genuine.' },
  { term: 'Grapple', definition: 'v. To struggle or wrestle with something.', example: 'The country is grappling with economic issues.' },
  { term: 'Habitual', definition: 'adj. Done regularly or repeatedly.', example: 'His habitual lateness annoyed his coworkers.' },
  { term: 'Haphazard', definition: 'adj. Lacking organization or planning.', example: 'The project was completed in a haphazard manner.' },
  { term: 'Hibernation', definition: 'n. A state of dormancy or deep sleep.', example: 'Many bear species go into hibernation during the winter.' },
  { term: 'Highlight', definition: 'v. To emphasize or make noticeable.', example: 'The article highlights key points of the debate.' },
  { term: 'Hinder', definition: 'v. To obstruct or slow progress.', example: 'The heavy traffic hindered our journey.' },
  { term: 'Hoard', definition: 'v. To accumulate and store excessively.', example: 'He hoarded food supplies and toilet paper during the pandemic.' },
  { term: 'Homogeneous', definition: 'adj. Uniform or similar throughout.', example: 'The population of the village is homogeneous.' },
  { term: 'Hypothesize', definition: 'v. To form a theory or assumption.', example: 'Scientists hypothesize about the origin of the universe.' },
  { term: 'Imaginative', definition: 'adj. Creative and full of new ideas.', example: "The artist's work is highly imaginative." },
  { term: 'Imitation', definition: 'n. A copy or replica of something.', example: 'The purse was an imitation of a designer brand.' },
  { term: 'Imminent', definition: 'adj. About to happen soon.', example: 'A storm is imminent according to the forecast.' },
  { term: 'Immune', definition: 'adj. Resistant to disease or harm.', example: "He's immune to the virus due to vaccination." },
  { term: 'Impartial', definition: 'adj. Fair and not biased.', example: 'Judges must always remain impartial during a trial.' },
  { term: 'Impending', definition: 'adj. Approaching or about to happen.', example: 'They prepared for the impending storm by boarding up windows.' },
  { term: 'Impenetrable', definition: 'adj. Impossible to pass through.', example: 'The fortress was impenetrable to enemy attack.' },
  { term: 'Imperceptible', definition: 'adj. Very slight or difficult to notice.', example: "Alex's reaction was imperceptible so I couldn't tell what he was thinking." },
  { term: 'Implement', definition: 'v. To put into effect or execute.', example: 'The business will implement new rules to comply with the change in laws.' },
  { term: 'Implication', definition: 'n. A possible consequence or meaning.', example: 'The policy change has serious implications for lobbyists.' },
  { term: 'Implicit', definition: 'adj. Implied rather than stated directly.', example: 'His approval was implicit in his silence.' },
  { term: 'Impractical', definition: 'adj. Not sensible or realistic.', example: 'The dress design was too impractical to actually wear.' },
  { term: 'Improvise', definition: 'v. To create or perform spontaneously.', example: 'The actor had to improvise when he forgot his lines.' },
  { term: 'Inactive', definition: 'adj. Not engaged in movement or activity.', example: 'The volcano has been inactive for decades.' },
  { term: 'Inadequate', definition: 'adj. Insufficient or lacking.', example: "I felt inadequate when I didn't make the final shot during the basketball game." },
  { term: 'Inadvertently', definition: 'adv. Unintentionally or by accident.', example: 'The new worker caused a ruckus when he inadvertently deleted an important file.' },
  { term: 'Incite', definition: 'v. to encourage or stir up', example: 'Her hateful words incited anger in the crowd.' },
  { term: 'Inconspicuous', definition: 'adj. Not being easily seen or noticed.', example: 'The spy was inconspicuous as he moved through the crowd.' },
  { term: 'Indecipherable', definition: 'adj. Impossible to understand or read.', example: 'His messy handwriting was indecipherable.' },
  { term: 'Indicate', definition: 'v. To point out or show.', example: 'The results indicate a positive trend.' },
  { term: 'Indifference', definition: 'n. Lack of interest or concern.', example: "Natalia's indifference to the situation frustrated her sisters." },
  { term: 'Indisputable', definition: 'adj. Unable to be challenged or denied.', example: 'Because the evidence was indisputable the lawyer was certain his client would go free.' },
  { term: 'Indistinct', definition: 'adj. Not clear or sharply defined.', example: 'The figure in the distance was blurry and indistinct.' },
  { term: 'Indulge', definition: 'v. To allow oneself to enjoy.', example: 'After a long day of work Jane decided to indulge in a piece of cake.' },
  { term: 'Ineffectual', definition: 'adj. Not producing the desired effect.', example: "The mayor's efforts to change the city's parking rules were ineffectual." },
  { term: 'Inevitable', definition: 'adj. Certain to happen; unavoidable.', example: 'You must accept that change is inevitable in life.' },
  { term: 'Inexpensive', definition: 'adj. Not costly.', example: 'The new Vietnamese restaurant down the street serves inexpensive but delicious meals.' },
  { term: 'Inexplicable', definition: 'adj. Unable to be explained.', example: "My uncle's sudden departure from the family reunion was inexplicable." },
  { term: 'Influence', definition: 'n. The power to affect others.', example: "The pastor's speech had a strong influence on the audience." },
  { term: 'Infrequent', definition: 'adj. Not occurring often.', example: 'Rain is infrequent in the Atacama Desert.' },
  { term: 'Inhibit', definition: 'v. To hinder or restrain.', example: 'Fear of failure can inhibit creativity.' },
  { term: 'Innocuous', definition: 'adj. Harmless or inoffensive.', example: 'The comment seemed innocuous but it upset him.' },
  { term: 'Insensible', definition: 'adj. Unaware or indifferent.', example: "The father was insensible to his children's boredom." },
  { term: 'Insignificant', definition: 'adj. Too small or unimportant to matter.', example: 'The difference in price between the two ice creams was insignificant.' },
  { term: 'Inspect', definition: 'v. To examine closely.', example: 'The contractor will inspect the building for safety.' },
  { term: 'Inspirational', definition: 'adj. Providing motivation or encouragement.', example: "Evan's story of recovering from a severe car accident was inspirational to many." },
  { term: 'Intangible', definition: 'adj. Not able to be touched or measured.', example: 'Love is an intangible concept.' },
  { term: 'Intentional', definition: 'adj. Done on purpose.', example: "By reading the evidence I could tell the man's actions were intentional." },
  { term: 'Interchangeable', definition: "adj. Able to be substituted for each other.", example: "These parts are interchangeable so it doesn't matter which one you use." },
  { term: 'Interject', definition: 'v. To insert a comment abruptly.', example: 'My brother interjected with a sarcastic remark.' },
  { term: 'Interpret', definition: 'v. To explain the meaning of something.', example: "I don't understand this poem; can you interpret it for me?" },
  { term: 'Intersect', definition: 'v. To cross or meet at a point.', example: 'The two streets intersect downtown.' },
  { term: 'Intricate', definition: 'adj. Very detailed or complicated.', example: 'The artist created an intricate design on the fabric.' },
  { term: 'Intriguing', definition: 'adj. Arousing curiosity or interest.', example: "The mystery novel was intriguing because I couldn't figure out who the murderer was." },
  { term: 'Invalidate', definition: 'v. To make something void or null.', example: 'The new evidence invalidated his argument.' },
  { term: 'Invent', definition: 'v. To create something new.', example: 'Thomas Edison invented the incandescent light bulb.' },
  { term: 'Investigation', definition: 'n. Systematic inquiries to uncover facts.', example: 'The police conducted a thorough investigation of the crime scene.' },
  { term: 'Involuntarily', definition: 'adv. Done without conscious control.', example: 'She involuntarily gasped in surprise.' },
  { term: 'Irrelevant', definition: 'adj. Not related or applicable.', example: 'His comment was irrelevant to the discussion.' },
  { term: 'Isolate', definition: 'v. To separate from others.', example: 'We need to isolate the patient with the very contagious disease.' },
  { term: 'Lacking', definition: 'adj. Not having enough of something.', example: 'The short essay was lacking in detail.' },
  { term: 'Latent', definition: 'adj. Present but not active.', example: 'He had a latent talent for music.' },
  { term: 'Legitimate', definition: 'adj. Lawful or valid.', example: "Because he was named in the will John's claim to the property was legitimate." },
  { term: 'Localized', definition: 'adj. Restricted to a particular area.', example: 'The disease was localized to one region.' },
  { term: 'Manageable', definition: 'adj. Able to be controlled or handled.', example: "I'm lucky that my workload is manageable today so I'll be home in time for dinner." },
  { term: 'Mandatory', definition: 'adj. Required or obligatory.', example: 'Attendance at the meeting is mandatory for all employees.' },
  { term: 'Mimic', definition: 'v. To imitate.', example: 'Parrots can mimic human speech.' },
  { term: 'Misanthropic', definition: 'adj. Disliking people or society.', example: 'The old man was known for his misanthropic views.' },
  { term: 'Misrepresent', definition: 'v. To give a false impression.', example: 'The article misrepresented the facts.' },
  { term: 'Moderate', definition: 'adj. Not extreme; average.', example: 'He never has strong opinions and most of his views are moderate.' },
  { term: 'Multifaceted', definition: 'adj. Having many aspects or features.', example: 'The housing problem is multifaceted and will take multiple solutions to solve.' },
  { term: 'Neglect', definition: 'v. To fail to care for properly.', example: 'He neglected his responsibilities when he decided to play video games instead of clean the house.' },
  { term: 'Neutrality', definition: 'n. The state of not taking sides.', example: 'Switzerland maintained neutrality during World War II.' },
  { term: 'Newfound', definition: 'adj. Recently discovered or developed.', example: 'The recently-released prisoner enjoyed his newfound freedom.' },
  { term: 'Notional', definition: 'adj. Existing only in theory.', example: "Because we hadn't started it the plan was still notional." },
  { term: 'Novel', definition: 'adj. New or original.', example: 'The doctor introduced a novel approach to hip surgery.' },
  { term: 'Nuanced', definition: 'adj. Having subtle differences.', example: 'His argument was well-developed and nuanced.' },
  { term: 'Obligate', definition: 'v. To compel or require.', example: 'The contract obligates him to pay.' },
  { term: 'Obscure', definition: 'adj. Not easily understood or seen.', example: "The meaning of the letter was obscure and I didn't know what to make of it." },
  { term: 'Observable', definition: 'adj. Able to be seen or noticed.', example: 'The rings of Saturn were observable through the telescope.' },
  { term: 'Observant', definition: 'adj. Quick to notice things.', example: 'The detective is very observant of small details.' },
  { term: 'Obsolete', definition: 'adj. no longer used; rare or uncommon', example: "Historians assumed record players would be obsolete by now but in fact they're making a huge comeback." },
  { term: 'Obstructed', definition: 'adj. Blocked or hindered.', example: "We couldn't leave town because the road was obstructed by fallen trees." },
  { term: 'Occupy', definition: 'v. To take up space or time.', example: 'The kids occupied themselves with games.' },
  { term: 'Oddity', definition: 'n. Something unusual or strange.', example: 'The museum displayed an interesting oddity.' },
  { term: 'Offhand', definition: 'adj. Done without preparation or thought.', example: 'His offhand remark surprised everyone.' },
  { term: 'Omnipotent', definition: 'adj. almighty and all powerful', example: 'Gods are omnipotent beings who can control human destiny.' },
  { term: 'Onset', definition: 'n. the beginning or early stages', example: 'At the onset of her career as a lawyer things were looking up.' },
  { term: 'Operative', definition: 'adj. Functioning or having effect.', example: 'The new policy is now operative so be sure to follow it.' },
  { term: 'Ornamental', definition: 'adj. Decorative rather than functional.', example: 'The garden was filled with ornamental plants that helped beautify the space.' },
  { term: 'Oust', definition: 'v. to remove or force out of a position or office', example: "Sick and tired of putting up with his bad moods the pirates ousted their captain." },
  { term: 'Outstrip', definition: 'v. To surpass or exceed.', example: 'Sales of my new novel outstripped all expectations.' },
  { term: 'Overcome', definition: 'v. To succeed in dealing with a problem.', example: 'She overcame her fear of public speaking and was able to deliver her remarks.' },
  { term: 'Overlook', definition: 'v. To fail to notice or consider.', example: 'The officer overlooked an important detail that would have helped solve the crime.' },
  { term: 'Overreact', definition: 'v. To respond too strongly.', example: "My sister overreacted to our parents' criticism of her outfit." },
  { term: 'Overshadow', definition: 'v. To be more important than something else.', example: 'His success overshadowed his past failures.' },
  { term: 'Overtly', definition: 'adv. Openly and clearly.', example: 'He overtly expressed his disapproval by telling me what he thought.' },
  { term: 'Overwhelmed', definition: 'adj. Feeling excessive stress or emotion.', example: "Agatha felt overwhelmed by her workload and had no idea how she'd finish it all in time." },
  { term: 'Paramount', definition: 'adj. predominant; superior; most important', example: 'Our paramount concern is the safety of our employees.' },
  { term: 'Paucity', definition: 'n. A scarcity or lack.', example: 'The crime will be difficult to solve because there is a paucity of evidence.' },
  { term: 'Perceive', definition: 'v. To become aware of something.', example: 'She perceived a hint of sadness in his voice.' },
  { term: 'Peripheral', definition: 'adj. On the edge or outer part of something.', example: "My involvement was peripheral to the project because I didn't do much." },
  { term: 'Permanent', definition: 'adj. Lasting indefinitely.', example: "The marker left a permanent stain on my favorite shirt that I won't be able to get out." },
  { term: 'Perpetual', definition: 'adj. Continuing forever or indefinitely.', example: 'The con artist lived in perpetual fear of being arrested.' },
  { term: 'Persistent', definition: 'adj. Continuing despite difficulty.', example: 'After fifty years of buying lottery tickets persistent efforts paid off when he won the jackpot.' },
  { term: 'Popularize', definition: 'v. To make widely known.', example: 'The internet popularized online shopping.' },
  { term: 'Postulate', definition: 'v. To assume or propose a theory.', example: 'Scientists postulated a new hypothesis for the origin of the universe.' },
  { term: 'Pragmatic', definition: 'adj. Practical and realistic.', example: 'Elliot put his emotions aside and took a pragmatic approach to problem-solving.' },
  { term: 'Praise', definition: 'v. To express approval or admiration.', example: "The teacher praised the students' hard work." },
  { term: 'Precarious', definition: 'adj. Uncertain or unstable.', example: 'The goat was perched on a precarious edge of the cliff.' },
  { term: 'Preclude', definition: 'v. To prevent from happening.', example: "Dylan's injury precluded him from playing in the soccer match." },
  { term: 'Predatory', definition: 'adj. Exploiting others for personal gain.', example: 'The credit company engaged in predatory lending practices.' },
  { term: 'Predetermined', definition: 'adj. Decided in advance.', example: 'The outcome seemed predetermined and that we could do nothing to change it.' },
  { term: 'Predict', definition: 'v. To say what will happen in the future.', example: 'Meteorologists predict rain tomorrow.' },
  { term: 'Premeditated', definition: 'adj. Planned beforehand.', example: 'Because the man had planned the theft for weeks it was obvious the crime was premeditated.' },
  { term: 'Prescribe', definition: 'v. To recommend or order a treatment.', example: 'The doctor prescribed antibiotics when I had an ear infection.' },
  { term: 'Preserve', definition: "v. To keep something in its original state.", example: "The builders worked to preserve the house's original decorations." },
  { term: 'Presume', definition: 'v. To assume something to be true.', example: "I presume he will be late to the party." },
  { term: 'Prevail', definition: 'v. To win or be more powerful.', example: 'Justice will always prevail.' },
  { term: 'Preventable', definition: 'adj. Able to be avoided.', example: 'Many diseases are preventable with vaccines.' },
  { term: 'Probability', definition: 'n. Likelihood of something happening.', example: "When you live in the desert there's almost always a low probability of rain." },
  { term: 'Proclaim', definition: 'v. To announce officially.', example: 'The king proclaimed a new law.' },
  { term: 'Produce', definition: 'v. To create or generate something.', example: 'The Ford factory produces thousands of cars each year.' },
  { term: 'Profusion', definition: 'n. A large quantity of something.', example: 'The garden had a profusion of flowers every spring.' },
  { term: 'Prolong', definition: 'v. To extend in duration.', example: 'He tried to prolong the meeting from one hour to two.' },
  { term: 'Prominent', definition: 'adj. Important or well-known.', example: 'Marie Curie was a prominent scientist who won many awards.' },
  { term: 'Proponent', definition: 'n. A supporter of a cause or idea.', example: 'The environmentalist was a proponent of renewable energy.' },
  { term: 'Provoke', definition: 'v. To stir up or incite.', example: "Miriam's rude words provoked an argument." },
  { term: 'Prudently', definition: 'adv. In a wise or careful manner.', example: 'My grandmother always prudently saved money for emergencies.' },
  { term: 'Quantity', definition: 'n. An amount or number.', example: 'The pudding recipe requires a small quantity of sugar.' },
  { term: 'Quarrel', definition: 'n. An angry argument or dispute.', example: 'The couple had a loud quarrel over money.' },
  { term: 'Questionable', definition: 'adj. Doubtful or uncertain.', example: "Despite claiming to want to help people the politician's motives were questionable." },
  { term: 'Ramify', definition: 'v. to split into two or more branches', example: 'Cars ramified throughout the world in the twentieth century.' },
  { term: 'Rarely', definition: 'adv. Infrequently or seldom.', example: 'My sister rarely eats fast food.' },
  { term: 'Rationalize', definition: 'v. To justify an action with reasoning.', example: 'He tried to rationalize his mistake by explaining his thought process.' },
  { term: 'Rebellion', definition: 'n. An act of resistance against authority.', example: 'The peasants led a rebellion against the king.' },
  { term: 'Recalcitrant', definition: 'adj. Stubbornly resistant to authority.', example: 'The recalcitrant student refused to obey.' },
  { term: 'Recant', definition: 'v. To take back a previous statement.', example: 'He was forced to recant his confession.' },
  { term: 'Receptive', definition: 'adj. Open to new ideas.', example: 'The new dancer was receptive to feedback.' },
  { term: 'Reciprocate', definition: 'v. To give in return.', example: "I reciprocated my brother's kindness by buying him dinner." },
  { term: 'Recognizable', definition: 'adj. Easily identified.', example: 'The Nike logo is instantly recognizable.' },
  { term: 'Rectify', definition: 'v. To correct or fix something.', example: 'She tried to rectify her mistake with an apology.' },
  { term: 'Redefine', definition: 'v. To change the meaning of something.', example: 'The company redefined its mission.' },
  { term: 'Redress', definition: 'v. To set right or remedy.', example: 'They sought to redress past injustices.' },
  { term: 'Reform', definition: 'v. To improve by making changes.', example: 'The government promised to reform the healthcare system.' },
  { term: 'Refuse', definition: 'v. To decline or reject.', example: 'Emilia refused the job offer.' },
  { term: 'Refute', definition: 'v. To prove false or incorrect.', example: 'The scientist refuted the claim that the Earth was flat.' },
  { term: 'Regrettable', definition: 'adj. Causing sorrow or disappointment.', example: "Forgetting my boyfriend's birthday was a regrettable mistake." },
  { term: 'Regulate', definition: 'v. To control or manage.', example: 'The government regulates nuclear energy facilities.' },
  { term: 'Reject', definition: 'v. To dismiss or refuse to accept.', example: "She rejected her boyfriend's proposal." },
  { term: 'Relocate', definition: 'v. To move to a new place.', example: 'The dentist relocated to a bigger office.' },
  { term: 'Renounce', definition: 'v. To give up or reject formally.', example: 'He renounced his citizenship after moving to a new country.' },
  { term: 'Replenish', definition: 'v. To refill or restore.', example: 'After we finished the lemonade the hostess replenished the pitcher.' },
  { term: 'Replicable', definition: 'adj. Able to be copied or repeated.', example: "The experiment's results were replicable." },
  { term: 'Representative', definition: 'n. A person acting on behalf of others.', example: "The company's representative spoke at the meeting." },
  { term: 'Repress', definition: 'v. To suppress or hold back.', example: 'Although devastated Jalen repressed his emotions.' },
  { term: 'Reprieve', definition: 'n. A temporary relief or delay.', example: 'Because the defendant needed surgery the judge granted a reprieve.' },
  { term: 'Repudiate', definition: 'v. To reject or disown.', example: "She repudiated the accusation that she'd stolen money from the company." },
  { term: 'Resilient', definition: 'adj. Able to recover quickly.', example: 'Even after setbacks the patient is very resilient.' },
  { term: 'Resolve', definition: 'v. To find a solution.', example: 'The warring siblings eventually resolved their differences.' },
  { term: 'Responsive', definition: 'adj. Reacting quickly or positively.', example: 'The team wanted to improve and was very responsive to feedback.' },
  { term: 'Restore', definition: 'v. To bring back to original condition.', example: 'The architecture team carefully restored the old house.' },
  { term: 'Restrain', definition: 'v. To hold back or limit.', example: 'Even though Tom was furious he restrained his anger.' },
  { term: 'Retain', definition: 'v. To keep or hold onto.', example: 'I use this pitcher to retain water for my herb garden.' },
  { term: 'Retaliate', definition: 'v. To respond to an attack.', example: 'After Celia yelled at Dom he retaliated with a counterattack.' },
  { term: 'Rousing', definition: 'adj. Exciting or stirring.', example: 'The speaker gave a rousing speech that brought the audience to its feet.' },
  { term: 'Rudimentary', definition: 'adj. Basic or simple.', example: 'The little boy only has a rudimentary understanding of math.' },
  { term: 'Sanction', definition: 'v. To authorize or approve.', example: 'The government sanctioned the project so construction will start soon.' },
  { term: 'Sanguine', definition: 'adj. Optimistic or hopeful.', example: 'He remained sanguine despite repeated setbacks.' },
  { term: 'Saturate', definition: 'v. To soak or fill completely.', example: 'The sponge was saturated with water.' },
  { term: 'Scorn', definition: 'v. to look down on with disdain', example: "It's difficult for me not to scorn those who use improper grammar." },
  { term: 'Scrutinize', definition: 'v. To examine closely.', example: "I'm going to have my lawyer scrutinize the contract." },
  { term: 'Secretive', definition: 'adj. Keeping things hidden.', example: 'He was secretive about his plans for Valentine\'s Day.' },
  { term: 'Sensitive', definition: 'adj. Easily affected or aware.', example: 'She is very sensitive to criticism.' },
  { term: 'Simulate', definition: 'v. To imitate or replicate.', example: 'The pilot simulated an emergency landing.' },
  { term: 'Sincerity', definition: 'n. The quality of being genuine.', example: 'His sincerity was evident in his speech.' },
  { term: 'Skeptical', definition: 'adj. Doubtful or questioning.', example: "The teacher was skeptical of the student's claim that the dog ate her homework." },
  { term: 'Sophisticated', definition: 'adj. Complex or refined.', example: "The building's design was intricate and sophisticated." },
  { term: 'Span', definition: 'n. The extent or length of something.', example: 'The Golden Gate Bridge has a long span.' },
  { term: 'Sparingly', definition: 'adv. insufficiently or meagerly or in a restricted manner', example: 'Due to my blood pressure I must eat salt sparingly.' },
  { term: 'Speculate', definition: 'v. To guess or theorize.', example: 'He speculated about the outcome of the soccer match.' },
  { term: 'Spurious', definition: 'adj. False or deceptive.', example: 'The claims were spurious and therefore thrown out in court.' },
  { term: 'Stark', definition: 'adj. Very plain; devoid of any details or features', example: 'Looking out at the stark landscape I felt a keen sense of isolation.' },
  { term: 'Strenuously', definition: 'adv. With great effort.', example: 'She strenuously denied the accusations against her.' },
  { term: 'Sturdily', definition: 'adv. Strongly or solidly.', example: 'The chair was sturdily built and had no chance of breaking.' },
  { term: 'Stymie', definition: 'v. To hinder or block.', example: 'The restoration project was stymied by a lack of funds.' },
  { term: 'Substantial', definition: 'adj. Large or important.', example: 'Jackie made a substantial donation to her alma mater.' },
  { term: 'Subtle', definition: 'adj. Hard to detect or analyze', example: 'The author gave a subtle hint as to who the murderer was.' },
  { term: 'Succumb', definition: 'v. To give in or surrender.', example: 'He succumbed to the temptation to eat the entire bag of gummy bears.' },
  { term: 'Superficial', definition: 'adj. Shallow or lacking depth.', example: "The candidate struggled to answer questions about policy because his knowledge was superficial." },
  { term: 'Supplement', definition: 'v. To add to something.', example: 'She supplemented her income by starting a side hustle.' },
  { term: 'Surmise', definition: 'v. To infer or guess.', example: 'He surmised the answer based on context clues.' },
  { term: 'Surpass', definition: 'v. To exceed or go beyond.', example: 'She surpassed expectations by winning the national spelling bee.' },
  { term: 'Surrender', definition: 'v. To give up or yield.', example: 'The weakened army surrendered to the enemy.' },
  { term: 'Susceptible', definition: 'adj. Easily influenced or affected.', example: 'With his weakened immune system Marcelo is susceptible to illness.' },
  { term: 'Synchronization', definition: 'n. The process of coordinating events.', example: 'The synchronization of lights helped traffic flow.' },
  { term: 'Tentative', definition: 'adj. Uncertain or not fully decided.', example: 'Our plans are tentative and may change.' },
  { term: 'Tenuous', definition: 'adj. Weak or insubstantial.', example: 'His argument was tenuous at best.' },
  { term: 'Theoretical', definition: 'adj. Based on theory rather than practice.', example: 'The idea remains theoretical until tested.' },
  { term: 'Theory', definition: 'n. A system of ideas intended to explain something.', example: "Einstein's theory of relativity changed physics." },
  { term: 'Thoughtfulness', definition: 'n. Consideration for others.', example: 'Her thoughtfulness made her a great friend.' },
  { term: 'Tranquil', definition: 'adj. Peaceful and calm.', example: 'The lake was tranquil at sunset.' },
  { term: 'Transform', definition: 'v. To change in form or appearance.', example: 'The caterpillar transformed into a butterfly.' },
  { term: 'Ubiquitous', definition: 'adj. Present everywhere.', example: 'Smartphones have become ubiquitous in society.' },
  { term: 'Uncontroversial', definition: 'adj. Not likely to cause disagreement.', example: 'The decision was uncontroversial and widely accepted.' },
  { term: 'Undeniable', definition: 'adj. Cannot be disputed.', example: "Simone Biles' talent as a gymnast is undeniable." },
  { term: 'Underscore', definition: 'v. To emphasize.', example: 'The report underscored the importance of safety.' },
  { term: 'Unimportant', definition: 'adj. Not significant.', example: 'The details were unimportant to the main issue.' },
  { term: 'Unintended', definition: 'adj. Not planned or meant.', example: 'The side effects of the medication were unintended.' },
  { term: 'Universal', definition: 'adj. Common to all.', example: 'The desire for love is universal.' },
  { term: 'Unmistakable', definition: 'adj. Clearly recognizable.', example: "Morgan Freeman's voice is unmistakable." },
  { term: 'Unobtrusive', definition: 'adj. Not attracting attention.', example: 'The waitress did her best to be unobtrusive while clearing the table.' },
  { term: 'Unoriginal', definition: 'adj. Lacking originality.', example: 'His speech was unoriginal and predictable.' },
  { term: 'Unpredictable', definition: 'adj. Difficult to foresee.', example: 'The weather in winter can often be unpredictable.' },
  { term: 'Validate', definition: 'v. To confirm the accuracy of something.', example: 'The test results validated his hypothesis.' },
  { term: 'Variable', definition: 'adj. Likely to change.', example: 'The weather is highly variable in spring.' },
  { term: 'Verisimilitude', definition: 'n. The appearance of being true or real.', example: "The novel's verisimilitude made it compelling." },
  { term: 'Veritable', definition: 'adj. Used to emphasize truth.', example: 'Einstein was a veritable genius.' },
  { term: 'Vigilance', definition: 'n. The action of keeping careful watch.', example: 'Constant vigilance is needed for security.' },
  { term: 'Vital', definition: 'adj. Urgently necessary', example: 'It is vital that you respond by the deadline.' },
  { term: 'Waive', definition: 'v. To give up a right or claim voluntarily.', example: 'He waived his right to an attorney.' },
  { term: 'Warranted', definition: 'adj. Justified or necessary.', example: 'The decision was warranted by the evidence.' },
  { term: 'Widespread', definition: 'adj. Found or occurring over a large area.', example: 'The disease became widespread.' },
  { term: 'Withdraw', definition: 'v. To remove or retreat.', example: 'She withdrew from the competition.' },
];

async function main() {
  const existing = await prisma.wordList.findFirst({
    where: { isAdmin: true, title: 'Default Vocabulary List' },
  });

  if (existing) {
    console.log('Default vocab list already exists, skipping seed.');
    return;
  }

  const list = await prisma.wordList.create({
    data: {
      title: 'Default Vocabulary List',
      description: 'A curated list of essential vocabulary words with definitions and example sentences.',
      isPublic: true,
      isAdmin: true,
      ownerId: null,
    },
  });

  await prisma.word.createMany({
    data: words.map((w) => ({ ...w, listId: list.id })),
  });

  console.log(`Seeded default vocab list with ${words.length} words (listId: ${list.id})`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
